// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool
{
    /// <summary> Client options for LanguageToolAPIClient. </summary>
    public partial class LanguageToolAPIClientOptions : ClientOptions
    {
        private const ServiceVersion LatestVersion = ServiceVersion.V1_1_2;

        /// <summary> The version of the service to use. </summary>
        public enum ServiceVersion
        {
            /// <summary> Service version "1.1.2". </summary>
            V1_1_2 = 1,
        }

        internal string Version { get; }

        /// <summary> Initializes new instance of LanguageToolAPIClientOptions. </summary>
        public LanguageToolAPIClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.V1_1_2 => "1.1.2",
                _ => throw new NotSupportedException()
            };
        }
    }
}
