// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    public partial class Get200ApplicationJsonItemsItem
    {
        internal static Get200ApplicationJsonItemsItem DeserializeGet200ApplicationJsonItemsItem(JsonElement element)
        {
            string name = default;
            string code = default;
            string longCode = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("code"))
                {
                    code = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("longCode"))
                {
                    longCode = property.Value.GetString();
                    continue;
                }
            }
            return new Get200ApplicationJsonItemsItem(name, code, longCode);
        }
    }
}
