// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The Get200ApplicationJsonItemsItem. </summary>
    public partial class Get200ApplicationJsonItemsItem
    {
        /// <summary> Initializes a new instance of Get200ApplicationJsonItemsItem. </summary>
        /// <param name="name"> a language name like &apos;French&apos; or &apos;English (Australia)&apos;. </param>
        /// <param name="code"> a language code like &apos;en&apos;. </param>
        /// <param name="longCode"> a language code like &apos;en-US&apos; or &apos;ca-ES-valencia&apos;. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="name"/>, <paramref name="code"/> or <paramref name="longCode"/> is null. </exception>
        internal Get200ApplicationJsonItemsItem(string name, string code, string longCode)
        {
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }
            if (code == null)
            {
                throw new ArgumentNullException(nameof(code));
            }
            if (longCode == null)
            {
                throw new ArgumentNullException(nameof(longCode));
            }

            Name = name;
            Code = code;
            LongCode = longCode;
        }

        /// <summary> a language name like &apos;French&apos; or &apos;English (Australia)&apos;. </summary>
        public string Name { get; }
        /// <summary> a language code like &apos;en&apos;. </summary>
        public string Code { get; }
        /// <summary> a language code like &apos;en-US&apos; or &apos;ca-ES-valencia&apos;. </summary>
        public string LongCode { get; }
    }
}
