// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    public partial class Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema
    {
        internal static Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema DeserializePaths19M51AqWordsGetResponses200ContentApplicationJsonSchema(JsonElement element)
        {
            Optional<IReadOnlyList<string>> words = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("words"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    words = array;
                    continue;
                }
            }
            return new Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema(Optional.ToList(words));
        }
    }
}
