// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema. </summary>
    public partial class Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema
    {
        /// <summary> Initializes a new instance of Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema. </summary>
        internal Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema()
        {
            Words = new ChangeTrackingList<string>();
        }

        /// <summary> Initializes a new instance of Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema. </summary>
        /// <param name="words"> array of words. </param>
        internal Paths19M51AqWordsGetResponses200ContentApplicationJsonSchema(IReadOnlyList<string> words)
        {
            Words = words;
        }

        /// <summary> array of words. </summary>
        public IReadOnlyList<string> Words { get; }
    }
}
