// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The PathsWjwd9LWordsDeletePostResponses200ContentApplicationJsonSchema. </summary>
    public partial class PathsWjwd9LWordsDeletePostResponses200ContentApplicationJsonSchema
    {
        /// <summary> Initializes a new instance of PathsWjwd9LWordsDeletePostResponses200ContentApplicationJsonSchema. </summary>
        internal PathsWjwd9LWordsDeletePostResponses200ContentApplicationJsonSchema()
        {
        }

        /// <summary> Initializes a new instance of PathsWjwd9LWordsDeletePostResponses200ContentApplicationJsonSchema. </summary>
        /// <param name="deleted"> true if the word has been removed. false means the word hasn&apos;t been removed because it was not in the dictionary. </param>
        internal PathsWjwd9LWordsDeletePostResponses200ContentApplicationJsonSchema(bool? deleted)
        {
            Deleted = deleted;
        }

        /// <summary> true if the word has been removed. false means the word hasn&apos;t been removed because it was not in the dictionary. </summary>
        public bool? Deleted { get; }
    }
}
