// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    public partial class Paths9LjlvoCheckPostResponses200ContentApplicationJsonSchemaPropertiesLanguagePropertiesDetectedlanguage
    {
        internal static Paths9LjlvoCheckPostResponses200ContentApplicationJsonSchemaPropertiesLanguagePropertiesDetectedlanguage DeserializePaths9LjlvoCheckPostResponses200ContentApplicationJsonSchemaPropertiesLanguagePropertiesDetectedlanguage(JsonElement element)
        {
            string name = default;
            string code = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("code"))
                {
                    code = property.Value.GetString();
                    continue;
                }
            }
            return new Paths9LjlvoCheckPostResponses200ContentApplicationJsonSchemaPropertiesLanguagePropertiesDetectedlanguage(name, code);
        }
    }
}
