// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema. </summary>
    public partial class PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema
    {
        /// <summary> Initializes a new instance of PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema. </summary>
        internal PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema()
        {
        }

        /// <summary> Initializes a new instance of PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema. </summary>
        /// <param name="added"> true if the word has been added. false means the word hasn&apos;t been added because it had been added before. </param>
        internal PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema(bool? added)
        {
            Added = added;
        }

        /// <summary> true if the word has been added. false means the word hasn&apos;t been added because it had been added before. </summary>
        public bool? Added { get; }
    }
}
