// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    public partial class PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema
    {
        internal static PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema DeserializePathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema(JsonElement element)
        {
            Optional<bool> added = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("added"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    added = property.Value.GetBoolean();
                    continue;
                }
            }
            return new PathsJ3J268WordsAddPostResponses200ContentApplicationJsonSchema(Optional.ToNullable(added));
        }
    }
}
