// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The Paths1Pou1GjWordsAddPostRequestbodyContentApplicationXWwwFormUrlencodedSchema. </summary>
    internal partial class Paths1Pou1GjWordsAddPostRequestbodyContentApplicationXWwwFormUrlencodedSchema
    {
        /// <summary> Initializes a new instance of Paths1Pou1GjWordsAddPostRequestbodyContentApplicationXWwwFormUrlencodedSchema. </summary>
        /// <param name="word"> The word to be added. Must not be a phrase, i.e. cannot contain white space. The word is added to a global dictionary that applies to all languages. </param>
        /// <param name="username"> Your username as used to log in at languagetool.org. </param>
        /// <param name="apiKey"> &lt;a target=&apos;_blank&apos; href=&apos;https://languagetool.org/editor/settings/api&apos;&gt;Your API key&lt;/a&gt;. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="word"/>, <paramref name="username"/> or <paramref name="apiKey"/> is null. </exception>
        internal Paths1Pou1GjWordsAddPostRequestbodyContentApplicationXWwwFormUrlencodedSchema(string word, string username, string apiKey)
        {
            if (word == null)
            {
                throw new ArgumentNullException(nameof(word));
            }
            if (username == null)
            {
                throw new ArgumentNullException(nameof(username));
            }
            if (apiKey == null)
            {
                throw new ArgumentNullException(nameof(apiKey));
            }

            Word = word;
            Username = username;
            ApiKey = apiKey;
        }

        /// <summary> The word to be added. Must not be a phrase, i.e. cannot contain white space. The word is added to a global dictionary that applies to all languages. </summary>
        public string Word { get; }
        /// <summary> Your username as used to log in at languagetool.org. </summary>
        public string Username { get; }
        /// <summary> &lt;a target=&apos;_blank&apos; href=&apos;https://languagetool.org/editor/settings/api&apos;&gt;Your API key&lt;/a&gt;. </summary>
        public string ApiKey { get; }
        /// <summary> Name of the dictionary to add the word to; non-existent dictionaries are created after calling this; if unset, adds to special default dictionary. </summary>
        public string Dict { get; }
    }
}
