// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The PostResponses200ContentApplicationJsonSchemaMatchesItemRule. </summary>
    public partial class PostResponses200ContentApplicationJsonSchemaMatchesItemRule
    {
        /// <summary> Initializes a new instance of PostResponses200ContentApplicationJsonSchemaMatchesItemRule. </summary>
        /// <param name="id"> An rule&apos;s identifier that&apos;s unique for this language. </param>
        /// <param name="description"></param>
        /// <param name="category"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/>, <paramref name="description"/> or <paramref name="category"/> is null. </exception>
        internal PostResponses200ContentApplicationJsonSchemaMatchesItemRule(string id, string description, Post200ApplicationJsonPropertiesItemsRuleCategory category)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (description == null)
            {
                throw new ArgumentNullException(nameof(description));
            }
            if (category == null)
            {
                throw new ArgumentNullException(nameof(category));
            }

            Id = id;
            Description = description;
            Urls = new ChangeTrackingList<Post200ApplicationJsonPropertiesItemsRuleUrlsItem>();
            Category = category;
        }

        /// <summary> Initializes a new instance of PostResponses200ContentApplicationJsonSchemaMatchesItemRule. </summary>
        /// <param name="id"> An rule&apos;s identifier that&apos;s unique for this language. </param>
        /// <param name="subId"> An optional sub identifier of the rule, used when several rules are grouped. </param>
        /// <param name="description"></param>
        /// <param name="urls"> An optional array of URLs with a more detailed description of the error. </param>
        /// <param name="issueType"> The &lt;a href=&quot;http://www.w3.org/International/multilingualweb/lt/drafts/its20/its20.html#lqissue-typevalues&quot;&gt;Localization Quality Issue Type&lt;/a&gt;. This is not defined for all languages, in which case it will always be &apos;Uncategorized&apos;. </param>
        /// <param name="category"></param>
        internal PostResponses200ContentApplicationJsonSchemaMatchesItemRule(string id, string subId, string description, IReadOnlyList<Post200ApplicationJsonPropertiesItemsRuleUrlsItem> urls, string issueType, Post200ApplicationJsonPropertiesItemsRuleCategory category)
        {
            Id = id;
            SubId = subId;
            Description = description;
            Urls = urls;
            IssueType = issueType;
            Category = category;
        }

        /// <summary> An rule&apos;s identifier that&apos;s unique for this language. </summary>
        public string Id { get; }
        /// <summary> An optional sub identifier of the rule, used when several rules are grouped. </summary>
        public string SubId { get; }
        /// <summary> Gets the description. </summary>
        public string Description { get; }
        /// <summary> An optional array of URLs with a more detailed description of the error. </summary>
        public IReadOnlyList<Post200ApplicationJsonPropertiesItemsRuleUrlsItem> Urls { get; }
        /// <summary> The &lt;a href=&quot;http://www.w3.org/International/multilingualweb/lt/drafts/its20/its20.html#lqissue-typevalues&quot;&gt;Localization Quality Issue Type&lt;/a&gt;. This is not defined for all languages, in which case it will always be &apos;Uncategorized&apos;. </summary>
        public string IssueType { get; }
        /// <summary> Gets the category. </summary>
        public Post200ApplicationJsonPropertiesItemsRuleCategory Category { get; }
    }
}
