// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The Post200ApplicationJsonPropertiesItemsRuleUrlsItem. </summary>
    public partial class Post200ApplicationJsonPropertiesItemsRuleUrlsItem
    {
        /// <summary> Initializes a new instance of Post200ApplicationJsonPropertiesItemsRuleUrlsItem. </summary>
        internal Post200ApplicationJsonPropertiesItemsRuleUrlsItem()
        {
        }

        /// <summary> Initializes a new instance of Post200ApplicationJsonPropertiesItemsRuleUrlsItem. </summary>
        /// <param name="value"> the URL. </param>
        internal Post200ApplicationJsonPropertiesItemsRuleUrlsItem(string value)
        {
            Value = value;
        }

        /// <summary> the URL. </summary>
        public string Value { get; }
    }
}
