// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    public partial class Post200ApplicationJsonProperties
    {
        internal static Post200ApplicationJsonProperties DeserializePost200ApplicationJsonProperties(JsonElement element)
        {
            string name = default;
            string version = default;
            string buildDate = default;
            int apiVersion = default;
            Optional<string> status = default;
            Optional<bool> premium = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("version"))
                {
                    version = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("buildDate"))
                {
                    buildDate = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("apiVersion"))
                {
                    apiVersion = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("status"))
                {
                    status = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("premium"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    premium = property.Value.GetBoolean();
                    continue;
                }
            }
            return new Post200ApplicationJsonProperties(name, version, buildDate, apiVersion, status.Value, Optional.ToNullable(premium));
        }
    }
}
