// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The Post200ApplicationJsonPropertiesItemsReplacementsItem. </summary>
    public partial class Post200ApplicationJsonPropertiesItemsReplacementsItem
    {
        /// <summary> Initializes a new instance of Post200ApplicationJsonPropertiesItemsReplacementsItem. </summary>
        internal Post200ApplicationJsonPropertiesItemsReplacementsItem()
        {
        }

        /// <summary> Initializes a new instance of Post200ApplicationJsonPropertiesItemsReplacementsItem. </summary>
        /// <param name="value"> the replacement string. </param>
        internal Post200ApplicationJsonPropertiesItemsReplacementsItem(string value)
        {
            Value = value;
        }

        /// <summary> the replacement string. </summary>
        public string Value { get; }
    }
}
