// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    public partial class Post200ApplicationJsonPropertiesItemsRuleCategory
    {
        internal static Post200ApplicationJsonPropertiesItemsRuleCategory DeserializePost200ApplicationJsonPropertiesItemsRuleCategory(JsonElement element)
        {
            Optional<string> id = default;
            Optional<string> name = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"))
                {
                    id = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
            }
            return new Post200ApplicationJsonPropertiesItemsRuleCategory(id.Value, name.Value);
        }
    }
}
