// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> If set to `picky`, additional rules will be activated, i.e. rules that you might only find useful when checking formal text. </summary>
    public readonly partial struct PostContentSchemaLevel : IEquatable<PostContentSchemaLevel>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="PostContentSchemaLevel"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public PostContentSchemaLevel(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string DefaultValue = "default";
        private const string PickyValue = "picky";

        /// <summary> default. </summary>
        public static PostContentSchemaLevel Default { get; } = new PostContentSchemaLevel(DefaultValue);
        /// <summary> picky. </summary>
        public static PostContentSchemaLevel Picky { get; } = new PostContentSchemaLevel(PickyValue);
        /// <summary> Determines if two <see cref="PostContentSchemaLevel"/> values are the same. </summary>
        public static bool operator ==(PostContentSchemaLevel left, PostContentSchemaLevel right) => left.Equals(right);
        /// <summary> Determines if two <see cref="PostContentSchemaLevel"/> values are not the same. </summary>
        public static bool operator !=(PostContentSchemaLevel left, PostContentSchemaLevel right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="PostContentSchemaLevel"/>. </summary>
        public static implicit operator PostContentSchemaLevel(string value) => new PostContentSchemaLevel(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is PostContentSchemaLevel other && Equals(other);
        /// <inheritdoc />
        public bool Equals(PostContentSchemaLevel other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
