// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace DidacticalEnigma.English.LanguageTool.Models
{
    /// <summary> The PostResponses200ContentApplicationJsonSchemaMatchesItemContext. </summary>
    public partial class PostResponses200ContentApplicationJsonSchemaMatchesItemContext
    {
        /// <summary> Initializes a new instance of PostResponses200ContentApplicationJsonSchemaMatchesItemContext. </summary>
        /// <param name="text"> Context of the error, i.e. the error and some text to the left and to the left. </param>
        /// <param name="offset"> The 0-based character offset of the error in the context text. </param>
        /// <param name="length"> The length of the error in characters in the context. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="text"/> is null. </exception>
        internal PostResponses200ContentApplicationJsonSchemaMatchesItemContext(string text, int offset, int length)
        {
            if (text == null)
            {
                throw new ArgumentNullException(nameof(text));
            }

            Text = text;
            Offset = offset;
            Length = length;
        }

        /// <summary> Context of the error, i.e. the error and some text to the left and to the left. </summary>
        public string Text { get; }
        /// <summary> The 0-based character offset of the error in the context text. </summary>
        public int Offset { get; }
        /// <summary> The length of the error in characters in the context. </summary>
        public int Length { get; }
    }
}
